In [23]:
import pandas as pd
import numpy as np

In [24]:
data=pd.read_csv(r"C:\Users\Asus\Documents\PythonData1200\Data Analytics Tool Analytics\youtube_dataset.csv", encoding='cp1252')

In [25]:
data.head()

  web-scraper-order                              web-scraper-start-url          userID                                        userID-href            name  uploads  subscribers   videoviews country    channeltype     usercreated grade YouTube_Link                                  YouTube_Link-href TwitterHandle                      TwitterHandle-href InstagramHandle                               InstagramHandle-href   MonthlyEarnings    YearlyEarnings
0   1553043067-5148  https://socialblade.com/youtube/top/5000/mosts...       PewDiePie        https://socialblade.com/youtube/c/pewdiepie       PewDiePie     3779     90210848  20772365682      US  Entertainment  Apr 29th, 2010     A          NaN  https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...           NaN           https://twitter.com/pewdiepie             NaN                    https://instagram.com/pewdiepie    €66.9K - €1.1M  €802.3K - €12.8M
1   1553043063-5147  https://socialblade.com/youtube/top/5000/mosts...        T-Series     https://socialblade.com/youtube/c/tseriesmusic        T-Series    13218     90194329  65092058996      IN          Music  Mar 13th, 2006   A++          NaN  https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...           NaN  https://instagram.com/tseries.official             NaN      https://plus.google.com/115156822320080163368  €635.6K - €10.2M     €7.6M - €122M
2   1553043059-5146  https://socialblade.com/youtube/top/5000/mosts...          Gaming  https://socialblade.com/youtube/channel/UCOpNc...          Gaming        0     81888222            0     NaN          Games  Dec 15th, 2013    D-          NaN  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           NaN                                     NaN             NaN  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           €0 - €0           €0 - €0
3   1553043055-5145  https://socialblade.com/youtube/top/5000/mosts...  YouTube Movies  https://socialblade.com/youtube/channel/UClgRk...  YouTube Movies        0     77413743            0     NaN           Film  Jun 10th, 2015    D-          NaN  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           NaN                                     NaN             NaN  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           €0 - €0           €0 - €0
4   1553043051-5144  https://socialblade.com/youtube/top/5000/mosts...          Sports  https://socialblade.com/youtube/channel/UCEgdi...          Sports        0     75622870            0     NaN         Sports  Dec 15th, 2013    D-          NaN  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           NaN                                     NaN             NaN  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           €0 - €0           €0 - €0

In [26]:
data.groupby('channeltype')['channeltype'].count()

channeltype
Animals             9
Autos              14
Comedy            275
Education         142
Entertainment    1037
Film              176
Games             449
Howto             223
Music             760
News               55
Nonprofit           3
People            392
Shows               1
Sports             56
Tech               78
Travel             11
Name: channeltype, dtype: int64

In [27]:
data.head(1000)

    web-scraper-order                              web-scraper-start-url          userID                                        userID-href            name  uploads  subscribers   videoviews country    channeltype     usercreated grade YouTube_Link                                  YouTube_Link-href TwitterHandle                        TwitterHandle-href InstagramHandle                               InstagramHandle-href   MonthlyEarnings    YearlyEarnings
0     1553043067-5148  https://socialblade.com/youtube/top/5000/mosts...       PewDiePie        https://socialblade.com/youtube/c/pewdiepie       PewDiePie     3779     90210848  20772365682      US  Entertainment  Apr 29th, 2010     A          NaN  https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...           NaN             https://twitter.com/pewdiepie             NaN                    https://instagram.com/pewdiepie    €66.9K - €1.1M  €802.3K - €12.8M
1     1553043063-5147  https://socialblade.com/youtube/top/5000/mosts...        T-Series     https://socialblade.com/youtube/c/tseriesmusic        T-Series    13218     90194329  65092058996      IN          Music  Mar 13th, 2006   A++          NaN  https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...           NaN    https://instagram.com/tseries.official             NaN      https://plus.google.com/115156822320080163368  €635.6K - €10.2M     €7.6M - €122M
2     1553043059-5146  https://socialblade.com/youtube/top/5000/mosts...          Gaming  https://socialblade.com/youtube/channel/UCOpNc...          Gaming        0     81888222            0     NaN          Games  Dec 15th, 2013    D-          NaN  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           NaN                                       NaN             NaN  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           €0 - €0           €0 - €0
3     1553043055-5145  https://socialblade.com/youtube/top/5000/mosts...  YouTube Movies  https://socialblade.com/youtube/channel/UClgRk...  YouTube Movies        0     77413743            0     NaN           Film  Jun 10th, 2015    D-          NaN  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           NaN                                       NaN             NaN  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           €0 - €0           €0 - €0
4     1553043051-5144  https://socialblade.com/youtube/top/5000/mosts...          Sports  https://socialblade.com/youtube/channel/UCEgdi...          Sports        0     75622870            0     NaN         Sports  Dec 15th, 2013    D-          NaN  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           NaN                                       NaN             NaN  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           €0 - €0           €0 - €0
..                ...                                                ...             ...                                                ...             ...      ...          ...          ...     ...            ...             ...   ...          ...                                                ...           ...                                       ...             ...                                                ...               ...               ...
995   1553037784-3900  https://socialblade.com/youtube/top/5000/mosts...   GloZell Green      https://socialblade.com/youtube/user/glozell1   GloZell Green     2316      4719893    845298432      US         Comedy  Jan 26th, 2008    B-          NaN  https://youtube.com/channel/UC7FhOuPmxz8spz_xv...           NaN            https://instagram.com/glozell/             NaN      https://plus.google.com/110057581739311657068      €228 - €3.7K    €2.7K - €43.8K
996   1553037792-3901  https://socialblade.com/youtube/top/5000/mosts...  ETV Jabardasth    https://socialblade.com/youtube/c/etvjabardasth  ETV Jabardasth     3735      4719652   4290216700      IN         People  Jul 14th, 2015     A          NaN  https://youtube.com/channel/UCnoqvTW4YZExfDeq7...           NaN                                       NaN             NaN  https://youtube.com/channel/UCnoqvTW4YZExfDeq7...    €50.5K - €808K     €606K - €9.7M
997   1553037768-3897  https://socialblade.com/youtube/top/5000/mosts...  The Timeliners    https://socialblade.com/youtube/c/thetimeliners  The Timeliners      191      4718880    459254149      IN  Entertainment   Feb 1st, 2014    B+          NaN  https://youtube.com/channel/UCTlnaHHQ75zlDg_fL...           NaN  https://www.instagram.com/thetimeliners/             NaN      https://plus.google.com/102509388716102017341    €5.6K - €90.3K    €67.7K - €1.1M
998   1553037724-3888  https://socialblade.com/youtube/top/5000/mosts...    Crafty Panda  https://socialblade.com/youtube/channel/UC03Rv...    Crafty Panda       84      4712345    890158507      US          Howto   Dec 3rd, 2017     A          NaN  https://youtube.com/channel/UC03RvJoIhm_fMwlUp...           NaN                                       NaN             NaN  https://youtube.com/channel/UC03RvJoIhm_fMwlUp...  €38.6K - €617.4K   €463.1K - €7.4M
999   1553037758-3896  https://socialblade.com/youtube/top/5000/mosts...  Troom Troom PT  https://socialblade.com/youtube/channel/UCgCQl...  Troom Troom PT      444      4711742    880150449     NaN            NaN  Apr 19th, 2015    A-          NaN  https://youtube.com/channel/UCgCQlMYN2XypwYC2w...           NaN       https://www.facebook.com/troomhands             NaN              https://www.instagram.com/troomtroom/  €16.4K - €261.8K   €196.3K - €3.1M

[1000 rows x 20 columns]

In [28]:
# Function to calculate the distributuion of channel type from the top 1000 records
def subset_data_channeltype_distribution(df, no_of_rows):
  subset = df.head(no_of_rows)
  return subset.groupby('channeltype')['channeltype'].count()


subset_data_channeltype_distribution(data,1000) # passing number of rows as a variable to make the function dynamic

channeltype
Animals            2
Autos              3
Comedy            76
Education         30
Entertainment    284
Film              36
Games            115
Howto             49
Music            240
News              17
Nonprofit          1
People            72
Sports            17
Tech              19
Travel             1
Name: channeltype, dtype: int64

In [29]:
#Top 1000 records inserted into a CSV file named youtube_dataset_top_1000_rows.csv
subset_data_frame = data.head(1000)
subset_data_frame.to_csv("youtube_dataset_top_1000_rows.csv", index=False)

In [30]:
import pandas as pd

first_1k_data = pd.read_csv(r"C:\Users\Asus\Documents\PythonData1200\Data Analytics Tool Analytics\youtube_dataset_top_1000_rows.csv")

In [11]:
first_1k_data

,web-scraper-order,web-scraper-start-url,userID,userID-href,name,uploads,subscribers,videoviews,country,channeltype,usercreated,grade,YouTube_Link,YouTube_Link-href,TwitterHandle,TwitterHandle-href,InstagramHandle,InstagramHandle-href,MonthlyEarnings,YearlyEarnings
0,1553043067-5148,https://socialblade.com/youtube/top/5000/mosts...,PewDiePie,https://socialblade.com/youtube/c/pewdiepie,PewDiePie,3779,90210848,20772365682,US,Entertainment,"Apr 29th, 2010",A,NaN,https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...,NaN,https://twitter.com/pewdiepie,NaN,https://instagram.com/pewdiepie,€66.9K - €1.1M,€802.3K - €12.8M
1,1553043063-5147,https://socialblade.com/youtube/top/5000/mosts...,T-Series,https://socialblade.com/youtube/c/tseriesmusic,T-Series,13218,90194329,65092058996,IN,Music,"Mar 13th, 2006",A++,NaN,https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...,NaN,https://instagram.com/tseries.official,NaN,https://plus.google.com/115156822320080163368,€635.6K - €10.2M,€7.6M - €122M
2,1553043059-5146,https://socialblade.com/youtube/top/5000/mosts...,Gaming,https://socialblade.com/youtube/channel/UCOpNc...,Gaming,0,81888222,0,NaN,Games,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,NaN,NaN,NaN,https://youtube.com/channel/UCOpNcN46UbXVtpKMr...,€0 - €0,€0 - €0
3,1553043055-5145,https://socialblade.com/youtube/top/5000/mosts...,YouTube Movies,https://socialblade.com/youtube/channel/UClgRk...,YouTube Movies,0,77413743,0,NaN,Film,"Jun 10th, 2015",D-,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,NaN,NaN,NaN,https://youtube.com/channel/UClgRkhTL3_hImCAmd...,€0 - €0,€0 - €0
4,1553043051-5144,https://socialblade.com/youtube/top/5000/mosts...,Sports,https://socialblade.com/youtube/channel/UCEgdi...,Sports,0,75622870,0,NaN,Sports,"Dec 15th, 2013",D-,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,NaN,NaN,NaN,https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...,€0 - €0,€0 - €0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1553037784-3900,https://socialblade.com/youtube/top/5000/mosts...,GloZell Green,https://socialblade.com/youtube/user/glozell1,GloZell Green,2316,4719893,845298432,US,Comedy,"Jan 26th, 2008",B-,NaN,https://youtube.com/channel/UC7FhOuPmxz8spz_xv...,NaN,https://instagram.com/glozell/,NaN,https://plus.google.com/110057581739311657068,€228 - €3.7K,€2.7K - €43.8K
996,1553037792-3901,https://socialblade.com/youtube/top/5000/mosts...,ETV Jabardasth,https://socialblade.com/youtube/c/etvjabardasth,ETV Jabardasth,3735,4719652,4290216700,IN,People,"Jul 14th, 2015",A,NaN,https://youtube.com/channel/UCnoqvTW4YZExfDeq7...,NaN,NaN,NaN,https://youtube.com/channel/UCnoqvTW4YZExfDeq7...,€50.5K - €808K,€606K - €9.7M
997,1553037768-3897,https://socialblade.com/youtube/top/5000/mosts...,The Timeliners,https://socialblade.com/youtube/c/thetimeliners,The Timeliners,191,4718880,459254149,IN,Entertainment,"Feb 1st, 2014",B+,NaN,https://youtube.com/channel/UCTlnaHHQ75zlDg_fL...,NaN,https://www.instagram.com/thetimeliners/,NaN,https://plus.google.com/102509388716102017341,€5.6K - €90.3K,€67.7K - €1.1M
998,1553037724-3888,https://socialblade.com/youtube/top/5000/mosts...,Crafty Panda,https://socialblade.com/youtube/channel/UC03Rv...,Crafty Panda,84,4712345,890158507,US,Howto,"Dec 3rd, 2017",A,NaN,https://youtube.com/channel/UC03RvJoIhm_fMwlUp...,NaN,NaN,NaN,https://youtube.com/channel/UC03RvJoIhm_fMwlUp...,€38.6K - €617.4K,€463.1K - €7.4M
999,1553037758-3896,https://socialblade.com/youtube/top/5000/mosts...,Troom Troom PT,https://socialblade.com/youtube/channel/UCgCQl...,Troom Troom PT,444,4711742,880150449,NaN,NaN,"Apr 19th, 2015",A-,NaN,https://youtube.com/channel/UCgCQlMYN2XypwYC2w...,NaN,https://www.facebook.com/troomhands,NaN,https://www.instagram.com/troomtroom/,€16.4K - €261.8K,€196.3K - €3.1M

In [31]:
from sqlalchemy import create_engine
sqlEngine = create_engine('mysql+pymysql://root:root@127.0.0.1')
dbConnection = sqlEngine.connect()
NEW_DB_NAME = 'youtube'

with sqlEngine.connect() as conn:
    conn.execute("commit")
    # Do not substitute user-supplied database names here.
    conn.execute(f"CREATE DATABASE Youtube")
    
first_1k_data.to_sql('youtube_data',con=sqlEngine, schema = 'youtube',index=False,if_exists='append')
frame = pd.read_sql("select * from youtube.youtube_data", dbConnection);
pd.set_option('display.expand_frame_repr', False)

In [32]:
frame

    web-scraper-order                              web-scraper-start-url          userID                                        userID-href            name  uploads  subscribers   videoviews country    channeltype     usercreated grade YouTube_Link                                  YouTube_Link-href TwitterHandle                        TwitterHandle-href InstagramHandle                               InstagramHandle-href   MonthlyEarnings    YearlyEarnings
0     1553043067-5148  https://socialblade.com/youtube/top/5000/mosts...       PewDiePie        https://socialblade.com/youtube/c/pewdiepie       PewDiePie     3779     90210848  20772365682      US  Entertainment  Apr 29th, 2010     A         None  https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd...          None             https://twitter.com/pewdiepie            None                    https://instagram.com/pewdiepie    €66.9K - €1.1M  €802.3K - €12.8M
1     1553043063-5147  https://socialblade.com/youtube/top/5000/mosts...        T-Series     https://socialblade.com/youtube/c/tseriesmusic        T-Series    13218     90194329  65092058996      IN          Music  Mar 13th, 2006   A++         None  https://youtube.com/channel/UCq-Fj5jknLsUf-MWS...          None    https://instagram.com/tseries.official            None      https://plus.google.com/115156822320080163368  €635.6K - €10.2M     €7.6M - €122M
2     1553043059-5146  https://socialblade.com/youtube/top/5000/mosts...          Gaming  https://socialblade.com/youtube/channel/UCOpNc...          Gaming        0     81888222            0    None          Games  Dec 15th, 2013    D-         None  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...          None                                      None            None  https://youtube.com/channel/UCOpNcN46UbXVtpKMr...           €0 - €0           €0 - €0
3     1553043055-5145  https://socialblade.com/youtube/top/5000/mosts...  YouTube Movies  https://socialblade.com/youtube/channel/UClgRk...  YouTube Movies        0     77413743            0    None           Film  Jun 10th, 2015    D-         None  https://youtube.com/channel/UClgRkhTL3_hImCAmd...          None                                      None            None  https://youtube.com/channel/UClgRkhTL3_hImCAmd...           €0 - €0           €0 - €0
4     1553043051-5144  https://socialblade.com/youtube/top/5000/mosts...          Sports  https://socialblade.com/youtube/channel/UCEgdi...          Sports        0     75622870            0    None         Sports  Dec 15th, 2013    D-         None  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...          None                                      None            None  https://youtube.com/channel/UCEgdi0XIXXZ-qJOFP...           €0 - €0           €0 - €0
..                ...                                                ...             ...                                                ...             ...      ...          ...          ...     ...            ...             ...   ...          ...                                                ...           ...                                       ...             ...                                                ...               ...               ...
995   1553037784-3900  https://socialblade.com/youtube/top/5000/mosts...   GloZell Green      https://socialblade.com/youtube/user/glozell1   GloZell Green     2316      4719893    845298432      US         Comedy  Jan 26th, 2008    B-         None  https://youtube.com/channel/UC7FhOuPmxz8spz_xv...          None            https://instagram.com/glozell/            None      https://plus.google.com/110057581739311657068      €228 - €3.7K    €2.7K - €43.8K
996   1553037792-3901  https://socialblade.com/youtube/top/5000/mosts...  ETV Jabardasth    https://socialblade.com/youtube/c/etvjabardasth  ETV Jabardasth     3735      4719652   4290216700      IN         People  Jul 14th, 2015     A         None  https://youtube.com/channel/UCnoqvTW4YZExfDeq7...          None                                      None            None  https://youtube.com/channel/UCnoqvTW4YZExfDeq7...    €50.5K - €808K     €606K - €9.7M
997   1553037768-3897  https://socialblade.com/youtube/top/5000/mosts...  The Timeliners    https://socialblade.com/youtube/c/thetimeliners  The Timeliners      191      4718880    459254149      IN  Entertainment   Feb 1st, 2014    B+         None  https://youtube.com/channel/UCTlnaHHQ75zlDg_fL...          None  https://www.instagram.com/thetimeliners/            None      https://plus.google.com/102509388716102017341    €5.6K - €90.3K    €67.7K - €1.1M
998   1553037724-3888  https://socialblade.com/youtube/top/5000/mosts...    Crafty Panda  https://socialblade.com/youtube/channel/UC03Rv...    Crafty Panda       84      4712345    890158507      US          Howto   Dec 3rd, 2017     A         None  https://youtube.com/channel/UC03RvJoIhm_fMwlUp...          None                                      None            None  https://youtube.com/channel/UC03RvJoIhm_fMwlUp...  €38.6K - €617.4K   €463.1K - €7.4M
999   1553037758-3896  https://socialblade.com/youtube/top/5000/mosts...  Troom Troom PT  https://socialblade.com/youtube/channel/UCgCQl...  Troom Troom PT      444      4711742    880150449    None           None  Apr 19th, 2015    A-         None  https://youtube.com/channel/UCgCQlMYN2XypwYC2w...          None       https://www.facebook.com/troomhands            None              https://www.instagram.com/troomtroom/  €16.4K - €261.8K   €196.3K - €3.1M

[1000 rows x 20 columns]